### ISSUE TITLE
Fonctionnalité

### ISSUE THREAD

**Issue by LFSAntonio** [MathieuRA/eldoras#1]
- Ajout de catégorie dans la boutique en fonction du type de véhicule.
- Type (Compact / Sportive / SUV ect...)

**Comment by MathieuRA** [comment]
Pourrais tu me transmettre tout le type de véhicules connus actuellement ?
Bien entendu, il y aura la possibilité d'en ajouter par la suite

**Comment by LFSAntonio** [comment]
Berlines | Camionnettes | Compactes | Coupés | Grosses cylindrées | Hélicoptères | Motos | Sportives | Sportives classiques | Super sportives | SUV | Tout-terrain | Ultralégères | Véhicules industriels |

**Comment by MathieuRA** [comment]
Au top. Je vais attaquer tout ce qui est backend une fois l'interface terminer

**Comment by MathieuRA** [comment]
@LFSAntonio Une véhicule peut t'il avoir plusieurs catégories différente ou il ne doit avoir q'une seul catégorie

**Comment by LFSAntonio** [comment]
Pas compris ta question 😅

**Comment by MathieuRA** [comment]
haha Mdrr

Grosso modo, un véhicule ne doit avoir que une catégorie, ou il peut en avoir plusieur ? 
Eg: (Voiture 1, Catégorie: SUV/TOUT Terrain) <- Ca c'est possible ou pas ?

**Comment by MathieuRA** [comment]
Bon je suis partie dans l'hypotese ou un véhicule peut avoir plusieur "type/catégorie"
Genre: SUV/Sportive

Je te laisse check ici pour le rendu actuelle. #2

La barre blanche sur le côté sera une barre de filtrage( par catégorie / nombre de parrainge / alphabétique / ... )

**Comment by LFSAntonio** [comment]
Normalement les catégories sont différentes car tu a :

SUV
TOUT TERRAINS
Ces deux catégories sont différentes

**Comment by LFSAntonio** [comment]
Les parrainages on pourra modifier ?
Car on va crée des véhicules exprès pour sa, et chaque mois les véhicules
changeront et il auront le choix entre trois véhicules lorsqu'il parraine 3
personnes.

**Comment by MathieuRA** [comment]
Oui bien entendu, la je développe juste le systeme d'affichage des véhicules. Tu fera afficher les véhicules que tu souhaite pas la suite.

Les véhicules afficher la sont juste pour faire de la mise en page atm

**Comment by LFSAntonio** [comment]
Ouais pas de soucis c'est noter 👌

**Comment by MathieuRA** [comment]
@LFSAntonio 
J'ai rajouter des screenshots de la nouvelle interface -> #2
Création d'une section parrainages avec les 3 véhicules du mois et création du catalogue.

Pour le catalogue, j'ai juste ajouter les véhicules parrainges pour faire de la mise en page vus que je n'ai pas le contenue du catalogue pour le moment, mais bien entendu ca sera les véhicules du catalogues du serv

Dit moi si c'est tout bon pour toi
